# Generated by Django 3.2 on 2023-01-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('property_price', models.IntegerField()),
                ('property_rent', models.IntegerField()),
                ('emi', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('other_exp', models.IntegerField()),
            ],
        ),
    ]
