# Generated by Django 3.2 on 2023-01-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='monthly_expenses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='monthly_income',
            field=models.IntegerField(default=0),
        ),
    ]
